
[general]
delay = 15

[twitter]
username = "querolerbot"
api_url = "https://api.twitter.com/"

[telegraph]
username = "@querolerbot"
url = "http://graph.org/"

# adicione mensagens aqui que o bot pode usar para responder
[messages]
success = [
    "Aqui está seu artigo sem paywall :)",
    "Bip, bop",
    "Saindo do forno ;)",
    "Tá sentindo? Cherinho de artigo sem paywall <3",
    "Ahoy",
    "Hello There..."
]

# mensagens de erro
[messages.error]
url_not_found = "Não achei nenhum link :("
text_not_found = "Infelizmente não consegui encontrar o texto ou o site ainda não é suportado :(\nVeja os sites compatíveis no meu perfil :)"

[database]
name = "articles.db"
